include balena-image.inc

BALENA_BOOT_PARTITION_FILES:append:imx6ul-var-dart = " \
    imx6ull-var-dart-6ulcustomboard-emmc-sd-card.dtb:/ \
    imx6ull-var-dart-6ulcustomboard-emmc-sd-card-wm8731.dtb:/ \
    imx6ull-var-dart-6ulcustomboard-emmc-wifi-brcm.dtb:/ \
    imx6ull-var-dart-6ulcustomboard-emmc-wifi-brcm-wm8731.dtb:/ \
    imx6ull-var-dart-6ulcustomboard-emmc-wifi-iw61x.dtb:/ \
    imx6ull-var-dart-6ulcustomboard-nand-sd-card.dtb:/ \
    imx6ull-var-dart-6ulcustomboard-nand-sd-card-wm8731.dtb:/ \
    imx6ull-var-dart-6ulcustomboard-nand-wifi-brcm.dtb:/ \
    imx6ull-var-dart-6ulcustomboard-nand-wifi-brcm-wm8731.dtb:/ \
    imx6ull-var-dart-6ulcustomboard-nand-wifi-iw61x.dtb:/ \
    imx6ull-var-som-concerto-board-emmc-sd-card.dtb:/ \
    imx6ull-var-som-concerto-board-emmc-sd-card-wm8731.dtb:/ \
    imx6ull-var-som-concerto-board-emmc-wifi.dtb:/ \
    imx6ull-var-som-concerto-board-emmc-wifi-wm8731.dtb:/ \
    imx6ull-var-som-concerto-board-nand-sd-card.dtb:/ \
    imx6ull-var-som-concerto-board-nand-sd-card-wm8731.dtb:/ \
    imx6ull-var-som-concerto-board-nand-wifi.dtb:/ \
    imx6ull-var-som-concerto-board-nand-wifi-wm8731.dtb:/ \
    imx6ull-var-som-symphony-board-emmc-sd-card.dtb:/ \
    imx6ull-var-som-symphony-board-emmc-sd-card-wm8731.dtb:/ \
    imx6ull-var-som-symphony-board-emmc-wifi.dtb:/ \
    imx6ull-var-som-symphony-board-emmc-wifi-wm8731.dtb:/ \
    imx6ull-var-som-symphony-board-nand-sd-card.dtb:/ \
    imx6ull-var-som-symphony-board-nand-sd-card-wm8731.dtb:/ \
    imx6ull-var-som-symphony-board-nand-wifi.dtb:/ \
    imx6ull-var-som-symphony-board-nand-wifi-wm8731.dtb:/ \
    imx6ul-var-dart-6ulcustomboard-emmc-sd-card.dtb:/ \
    imx6ul-var-dart-6ulcustomboard-emmc-sd-card-wm8731.dtb:/ \
    imx6ul-var-dart-6ulcustomboard-emmc-wifi-brcm.dtb:/ \
    imx6ul-var-dart-6ulcustomboard-emmc-wifi-brcm-wm8731.dtb:/ \
    imx6ul-var-dart-6ulcustomboard-emmc-wifi-iw61x.dtb:/ \
    imx6ul-var-dart-6ulcustomboard-nand-sd-card.dtb:/ \
    imx6ul-var-dart-6ulcustomboard-nand-sd-card-wm8731.dtb:/ \
    imx6ul-var-dart-6ulcustomboard-nand-wifi-brcm.dtb:/ \
    imx6ul-var-dart-6ulcustomboard-nand-wifi-brcm-wm8731.dtb:/ \
    imx6ul-var-dart-6ulcustomboard-nand-wifi-iw61x.dtb:/ \
    imx6ul-var-som-concerto-board-emmc-sd-card.dtb:/ \
    imx6ul-var-som-concerto-board-emmc-sd-card-wm8731.dtb:/ \
    imx6ul-var-som-concerto-board-emmc-wifi.dtb:/ \
    imx6ul-var-som-concerto-board-emmc-wifi-wm8731.dtb:/ \
    imx6ul-var-som-concerto-board-nand-sd-card.dtb:/ \
    imx6ul-var-som-concerto-board-nand-sd-card-wm8731.dtb:/ \
    imx6ul-var-som-concerto-board-nand-wifi.dtb:/ \
    imx6ul-var-som-concerto-board-nand-wifi-wm8731.dtb:/ \
    imx6ul-var-som-symphony-board-emmc-sd-card.dtb:/ \
    imx6ul-var-som-symphony-board-emmc-sd-card-wm8731.dtb:/ \
    imx6ul-var-som-symphony-board-emmc-wifi.dtb:/ \
    imx6ul-var-som-symphony-board-emmc-wifi-wm8731.dtb:/ \
    imx6ul-var-som-symphony-board-nand-sd-card.dtb:/ \
    imx6ul-var-som-symphony-board-nand-sd-card-wm8731.dtb:/ \
    imx6ul-var-som-symphony-board-nand-wifi.dtb:/ \
    imx6ul-var-som-symphony-board-nand-wifi-wm8731.dtb:/ \
    imx6ulz-var-dart-6ulcustomboard-emmc-sd-card.dtb:/ \
    imx6ulz-var-dart-6ulcustomboard-emmc-sd-card-wm8731.dtb:/ \
    imx6ulz-var-dart-6ulcustomboard-emmc-wifi-brcm.dtb:/ \
    imx6ulz-var-dart-6ulcustomboard-emmc-wifi-brcm-wm8731.dtb:/ \
    imx6ulz-var-dart-6ulcustomboard-emmc-wifi-iw61x.dtb:/ \
    imx6ulz-var-dart-6ulcustomboard-nand-sd-card.dtb:/ \
    imx6ulz-var-dart-6ulcustomboard-nand-sd-card-wm8731.dtb:/ \
    imx6ulz-var-dart-6ulcustomboard-nand-wifi-brcm.dtb:/ \
    imx6ulz-var-dart-6ulcustomboard-nand-wifi-brcm-wm8731.dtb:/ \
    imx6ulz-var-dart-6ulcustomboard-nand-wifi-iw61x.dtb:/ \
    imx6ulz-var-som-concerto-board-emmc-sd-card.dtb:/ \
    imx6ulz-var-som-concerto-board-emmc-sd-card-wm8731.dtb:/ \
    imx6ulz-var-som-concerto-board-emmc-wifi.dtb:/ \
    imx6ulz-var-som-concerto-board-emmc-wifi-wm8731.dtb:/ \
    imx6ulz-var-som-concerto-board-nand-sd-card.dtb:/ \
    imx6ulz-var-som-concerto-board-nand-sd-card-wm8731.dtb:/ \
    imx6ulz-var-som-concerto-board-nand-wifi.dtb:/ \
    imx6ulz-var-som-concerto-board-nand-wifi-wm8731.dtb:/ \
    imx6ulz-var-som-symphony-board-emmc-sd-card.dtb:/ \
    imx6ulz-var-som-symphony-board-emmc-sd-card-wm8731.dtb:/ \
    imx6ulz-var-som-symphony-board-emmc-wifi.dtb:/ \
    imx6ulz-var-som-symphony-board-emmc-wifi-wm8731.dtb:/ \
    imx6ulz-var-som-symphony-board-nand-sd-card.dtb:/ \
    imx6ulz-var-som-symphony-board-nand-sd-card-wm8731.dtb:/ \
    imx6ulz-var-som-symphony-board-nand-wifi.dtb:/ \
    imx6ulz-var-som-symphony-board-nand-wifi-wm8731.dtb:/ \
"

BALENA_BOOT_PARTITION_FILES:append:var-som-mx6 = " \
    imx6dl-var-som-cap.dtb:/imx6dl-var-som-cap.dtb \
    imx6dl-var-som-res.dtb:/imx6dl-var-som-res.dtb \
    imx6dl-var-som-solo-cap.dtb:/imx6dl-var-som-solo-cap.dtb \
    imx6dl-var-som-solo-res.dtb:/imx6dl-var-som-solo-res.dtb \
    imx6dl-var-som-solo-vsc.dtb:/imx6dl-var-som-solo-vsc.dtb \
    imx6dl-var-som-vsc.dtb:/imx6dl-var-som-vsc.dtb \
    imx6q-var-dart.dtb:/imx6q-var-dart.dtb \
    imx6q-var-som-cap.dtb:/imx6q-var-som-cap.dtb \
    imx6q-var-som-res.dtb:/imx6q-var-som-res.dtb \
    imx6q-var-som-vsc.dtb:/imx6q-var-som-vsc.dtb \
    imx6qp-var-som-cap.dtb:/imx6qp-var-som-cap.dtb \
    imx6qp-var-som-res.dtb:/imx6qp-var-som-res.dtb \
    imx6qp-var-som-vsc.dtb:/imx6qp-var-som-vsc.dtb \
"

BALENA_BOOT_PARTITION_FILES:append:imx7-var-som = " \
    imx7d-var-som-emmc-m4.dtb:/imx7d-var-som-emmc-m4.dtb \
    imx7d-var-som-emmc.dtb:/imx7d-var-som-emmc.dtb \
    imx7d-var-som-nand-m4.dtb:/imx7d-var-som-nand-m4.dtb \
    imx7d-var-som-nand.dtb:/imx7d-var-som-nand.dtb \
"
